---
title: "Productivity Prediction"
subtitle: "Analysis Report"
author: "Alvaro Manzanas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmdformats::html_clean:
    code_folding: hide
    self_contained: true
    number_sections: true
    thumbnails: false
    lightbox: true
    highlight: breezedark
  pdf_document:
    latex_engine: xelatex
    toc: true
    fig_caption: true
    number_sections: true
    keep_tex: false
    citation_package: natbib
pkgdown:
  as_is: true
editor_options: 
  markdown: 
    wrap: 79
bibliography: references.bib
always_allow_html: true
---

# Dataset

## Variable Information

1.  `date` : Date in MM-DD-YYYY
2.  `day` : Day of the Week
3.  `quarter` : A portion of the month. A month was divided into four quarters
4.  `department` : Associated department with the instance
5.  `team_no` : Associated team number with the instance
6.  `no_of_workers` : Number of workers in each team
7.  `no_of_style_change` : Number of changes in the style of a particular product
8.  `targeted_productivity` : Targeted productivity set by the Authority for each
    team for each day.
9.  `smv` : Standard Minute Value, it is the allocated time for a task
10. `wip` : Work in progress. Includes the number of unfinished items for
    products
11. `over_time` : Represents the amount of overtime by each team in minutes
12. `incentive` : Represents the amount of financial incentive (in BDT) that
    enables or motivates a particular course of action.
13. `idle_time` : The amount of time when the production was interrupted due to
    several reasons
14. `idle_men` : The number of workers who were idle due to production
    interruption
15. `actual_productivity` : The actual % of productivity that was delivered by
    the workers. It ranges from 0-1.

